import type { Company } from "../components/models/company";

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "Tata Consultancy Services (TCS)",
    logo: "/public/tech-company-logo.jpg",
    location: "Mumbai",
    industry: "Technology",
    description:
      "Global leader in IT services, consulting, and business solutions.",
    employees: 600000,
    founded: 1968,
    website: "www.tcs.com",
    revenue: "$27B",
    rating: 4.8,
    followers: 900000,
  },
  {
    id: "2",
    name: "Infosys",
    logo: "/public/innovation-lab-logo.png",
    location: "Bengaluru",
    industry: "Software",
    description: "Next-generation digital services and consulting company.",
    employees: 340000,
    founded: 1981,
    website: "www.infosys.com",
    revenue: "$18B",
    rating: 4.7,
    followers: 850000,
  },
  {
    id: "3",
    name: "Wipro",
    logo: "/renewable-energy-logo.jpg",
    location: "Bengaluru",
    industry: "Technology",
    description:
      "Global information technology, consulting, and business process services.",
    employees: 260000,
    founded: 1945,
    website: "www.wipro.com",
    revenue: "$11B",
    rating: 4.6,
    followers: 770000,
  },
  {
    id: "4",
    name: "HCL Technologies",
    logo: "/fintech-logo.png",
    location: "Noida",
    industry: "Technology",
    description:
      "Global IT services company delivering digital transformation solutions.",
    employees: 225000,
    founded: 1976,
    website: "www.hcltech.com",
    revenue: "$13B",
    rating: 4.6,
    followers: 720000,
  },
  {
    id: "5",
    name: "Tech Mahindra",
    logo: "/healthcare-technology-logo.jpg",
    location: "Pune",
    industry: "Technology",
    description:
      "Digital transformation and consulting services across industries.",
    employees: 150000,
    founded: 1986,
    website: "www.techmahindra.com",
    revenue: "$6.5B",
    rating: 4.5,
    followers: 680000,
  },
  {
    id: "6",
    name: "Deloitte",
    logo: "/construction-industry-logo.jpg",
    location: "Hyderabad",
    industry: "Consulting",
    description:
      "World’s largest consulting and professional services organization.",
    employees: 450000,
    founded: 1845,
    website: "www.deloitte.com",
    revenue: "$59B",
    rating: 4.9,
    followers: 1400000,
  },
  {
    id: "7",
    name: "Accenture",
    logo: "/retail-commerce-logo.jpg",
    location: "Bengaluru",
    industry: "Consulting",
    description:
      "Global professional services company specializing in IT and consulting.",
    employees: 720000,
    founded: 1989,
    website: "www.accenture.com",
    revenue: "$64B",
    rating: 4.9,
    followers: 2000000,
  },
  {
    id: "8",
    name: "Capgemini",
    logo: "/data-analytics-logo.jpg",
    location: "Mumbai",
    industry: "Technology",
    description:
      "Global leader in consulting, digital transformation, and engineering services.",
    employees: 350000,
    founded: 1967,
    website: "www.capgemini.com",
    revenue: "$22B",
    rating: 4.7,
    followers: 1100000,
  },
  {
    id: "9",
    name: "Cognizant",
    logo: "/public/tech-company-logo.jpg",
    location: "Chennai",
    industry: "Technology",
    description:
      "Leading professional services company transforming business models.",
    employees: 325000,
    founded: 1994,
    website: "www.cognizant.com",
    revenue: "$19B",
    rating: 4.6,
    followers: 900000,
  },
  {
    id: "10",
    name: "IBM",
    logo: "/public/innovation-lab-logo.png",
    location: "Bengaluru",
    industry: "Technology",
    description:
      "Global technology and consulting company known for AI and cloud.",
    employees: 288000,
    founded: 1911,
    website: "www.ibm.com",
    revenue: "$60B",
    rating: 4.8,
    followers: 2200000,
  },
  {
    id: "11",
    name: "Google",
    logo: "/renewable-energy-logo.jpg",
    location: "Hyderabad",
    industry: "Technology",
    description: "World’s leading search engine and cloud technology provider.",
    employees: 190000,
    founded: 1998,
    website: "www.google.com",
    revenue: "$300B",
    rating: 5.0,
    followers: 5000000,
  },
  {
    id: "12",
    name: "Microsoft",
    logo: "/fintech-logo.png",
    location: "Hyderabad",
    industry: "Technology",
    description:
      "Global leader in software, cloud computing, and enterprise tools.",
    employees: 230000,
    founded: 1975,
    website: "www.microsoft.com",
    revenue: "$250B",
    rating: 4.9,
    followers: 4800000,
  },
  {
    id: "13",
    name: "Amazon",
    logo: "/healthcare-technology-logo.jpg",
    location: "Hyderabad",
    industry: "Technology",
    description: "World’s largest e-commerce and cloud services provider.",
    employees: 1500000,
    founded: 1994,
    website: "www.amazon.com",
    revenue: "$575B",
    rating: 4.9,
    followers: 5200000,
  },
  {
    id: "14",
    name: "Oracle",
    logo: "/construction-industry-logo.jpg",
    location: "Bengaluru",
    industry: "Technology",
    description:
      "Leading provider of database software and cloud engineering systems.",
    employees: 160000,
    founded: 1977,
    website: "www.oracle.com",
    revenue: "$50B",
    rating: 4.7,
    followers: 900000,
  },
  {
    id: "15",
    name: "SAP",
    logo: "/retail-commerce-logo.jpg",
    location: "Bengaluru",
    industry: "Software",
    description:
      "Global leader in enterprise software and business applications.",
    employees: 110000,
    founded: 1972,
    website: "www.sap.com",
    revenue: "$33B",
    rating: 4.6,
    followers: 800000,
  },
  {
    id: "16",
    name: "Mindtree",
    logo: "/data-analytics-logo.jpg",
    location: "Bengaluru",
    industry: "Technology",
    description: "Global technology consulting and digital solutions provider.",
    employees: 38000,
    founded: 1999,
    website: "www.mindtree.com",
    revenue: "$1.4B",
    rating: 4.5,
    followers: 400000,
  },
  {
    id: "17",
    name: "L&T Infotech",
    logo: "/public/tech-company-logo.jpg",
    location: "Mumbai",
    industry: "Technology",
    description: "Global IT services and digital transformation company.",
    employees: 45000,
    founded: 1997,
    website: "www.lntinfotech.com",
    revenue: "$2.2B",
    rating: 4.5,
    followers: 350000,
  },
  {
    id: "18",
    name: "DXC Technology",
    logo: "/public/innovation-lab-logo.png",
    location: "Hyderabad",
    industry: "Technology",
    description:
      "Global IT services leader in cloud and modern workplace solutions.",
    employees: 130000,
    founded: 2017,
    website: "www.dxc.com",
    revenue: "$14B",
    rating: 4.4,
    followers: 500000,
  },
  {
    id: "19",
    name: "Genpact",
    logo: "/renewable-energy-logo.jpg",
    location: "Hyderabad",
    industry: "Finance",
    description: "Digital transformation company helping businesses innovate.",
    employees: 115000,
    founded: 1997,
    website: "www.genpact.com",
    revenue: "$4.4B",
    rating: 4.4,
    followers: 480000,
  },
  {
    id: "20",
    name: "Mphasis",
    logo: "/fintech-logo.png",
    location: "Bengaluru",
    industry: "Technology",
    description: "Leading provider of cloud and cognitive IT solutions.",
    employees: 32000,
    founded: 2000,
    website: "www.mphasis.com",
    revenue: "$1.6B",
    rating: 4.4,
    followers: 250000,
  },
  {
    id: "21",
    name: "UST Global",
    logo: "/healthcare-technology-logo.jpg",
    location: "Chennai",
    industry: "Technology",
    description: "Digital technology and IT solutions provider globally.",
    employees: 30000,
    founded: 1999,
    website: "www.ust.com",
    revenue: "$1B",
    rating: 4.3,
    followers: 220000,
  },
  {
    id: "22",
    name: "Zensar Technologies",
    logo: "/construction-industry-logo.jpg",
    location: "Pune",
    industry: "Technology",
    description:
      "Technology services company specializing in digital solutions.",
    employees: 11000,
    founded: 1991,
    website: "www.zensar.com",
    revenue: "$550M",
    rating: 4.3,
    followers: 150000,
  },
  {
    id: "23",
    name: "Birlasoft",
    logo: "/retail-commerce-logo.jpg",
    location: "Noida",
    industry: "Technology",
    description: "Enterprise digital and IT transformation services provider.",
    employees: 12000,
    founded: 1995,
    website: "www.birlasoft.com",
    revenue: "$500M",
    rating: 4.3,
    followers: 140000,
  },
  {
    id: "24",
    name: "Hexaware Technologies",
    logo: "/data-analytics-logo.jpg",
    location: "Mumbai",
    industry: "Technology",
    description:
      "Leading IT and business process outsourcing services provider.",
    employees: 25000,
    founded: 1990,
    website: "www.hexaware.com",
    revenue: "$1B",
    rating: 4.4,
    followers: 210000,
  },
  {
    id: "25",
    name: "Persistent Systems",
    logo: "/public/tech-company-logo.jpg",
    location: "Pune",
    industry: "Software",
    description: "Specializes in cloud, AI, and product engineering services.",
    employees: 23000,
    founded: 1990,
    website: "www.persistent.com",
    revenue: "$820M",
    rating: 4.6,
    followers: 300000,
  },
  {
    id: "26",
    name: "EY (Ernst & Young)",
    logo: "/public/innovation-lab-logo.png",
    location: "Bengaluru",
    industry: "Consulting",
    description:
      "One of the Big Four consulting firms specializing in assurance and IT advisory.",
    employees: 400000,
    founded: 1989,
    website: "www.ey.com",
    revenue: "$50B",
    rating: 4.9,
    followers: 1300000,
  },
  {
    id: "27",
    name: "PwC",
    logo: "/renewable-energy-logo.jpg",
    location: "Hyderabad",
    industry: "Consulting",
    description:
      "One of the Big Four professional services firms specializing in technology advisory.",
    employees: 325000,
    founded: 1998,
    website: "www.pwc.com",
    revenue: "$49B",
    rating: 4.8,
    followers: 1200000,
  },
  {
    id: "28",
    name: "KPMG",
    logo: "/fintech-logo.png",
    location: "Bengaluru",
    industry: "Consulting",
    description:
      "Big Four consulting firm providing audit, tax, and tech advisory.",
    employees: 265000,
    founded: 1987,
    website: "www.kpmg.com",
    revenue: "$34B",
    rating: 4.8,
    followers: 1000000,
  },
  {
    id: "29",
    name: "Tata Elxsi",
    logo: "/healthcare-technology-logo.jpg",
    location: "Bengaluru",
    industry: "Technology",
    description:
      "Design, engineering, and technology services for automotive and media.",
    employees: 12000,
    founded: 1989,
    website: "www.tataelxsi.com",
    revenue: "$700M",
    rating: 4.5,
    followers: 180000,
  },
  {
    id: "30",
    name: "Virtusa",
    logo: "/construction-industry-logo.jpg",
    location: "Hyderabad",
    industry: "Software",
    description: "Global IT consulting and digital engineering company.",
    employees: 30000,
    founded: 1996,
    website: "www.virtusa.com",
    revenue: "$1.3B",
    rating: 4.4,
    followers: 260000,
  },
  {
    id: "201",
    name: "Mumbai SoftLabs",
    logo: "/public/tech-company-logo.jpg",
    location: "Mumbai",
    industry: "Software",
    description:
      "Enterprise-grade SaaS application development and automation.",
    employees: 1800,
    founded: 2016,
    website: "www.mumbaisoftwarelabs.com",
    revenue: "$120M",
    rating: 4.6,
    followers: 98000,
  },
  {
    id: "202",
    name: "Skyline Software Solutions",
    logo: "/public/innovation-lab-logo.png",
    location: "Mumbai",
    industry: "Software",
    description: "Cloud-native engineering and digital product services.",
    employees: 2400,
    founded: 2014,
    website: "www.skylinesoftsolutions.com",
    revenue: "$160M",
    rating: 4.5,
    followers: 87000,
  },
  {
    id: "203",
    name: "NextWave Software India",
    logo: "/data-analytics-logo.jpg",
    location: "Mumbai",
    industry: "Software",
    description: "Specialized in AI-driven enterprise workflow software.",
    employees: 2100,
    founded: 2017,
    website: "www.nextwavesoftware.in",
    revenue: "$140M",
    rating: 4.7,
    followers: 90000,
  },
  {
    id: "204",
    name: "CoreLogic Systems",
    logo: "/public/tech-company-logo.jpg",
    location: "Mumbai",
    industry: "Software",
    description: "FinTech and enterprise payment software development.",
    employees: 1500,
    founded: 2015,
    website: "www.corelogicsystems.in",
    revenue: "$110M",
    rating: 4.4,
    followers: 76000,
  },
  {
    id: "205",
    name: "Mumbai CodeWorks",
    logo: "/public/innovation-lab-logo.png",
    location: "Mumbai",
    industry: "Software",
    description: "End-to-end custom web and mobile application development.",
    employees: 1900,
    founded: 2018,
    website: "www.mumbaicodeworks.com",
    revenue: "$95M",
    rating: 4.6,
    followers: 82000,
  },

  // ----------------- Bengaluru (5) -----------------
  {
    id: "206",
    name: "Bengaluru DevHub",
    logo: "/construction-industry-logo.jpg",
    location: "Bengaluru",
    industry: "Software",
    description: "Full-stack engineering and SaaS platform experts.",
    employees: 2600,
    founded: 2016,
    website: "www.blrdevhub.com",
    revenue: "$150M",
    rating: 4.7,
    followers: 110000,
  },
  {
    id: "207",
    name: "SouthTech Systems",
    logo: "/public/tech-company-logo.jpg",
    location: "Bengaluru",
    industry: "Software",
    description: "Enterprise microservices and cloud modernization partner.",
    employees: 2800,
    founded: 2015,
    website: "www.southtechsystems.in",
    revenue: "$180M",
    rating: 4.6,
    followers: 103000,
  },
  {
    id: "208",
    name: "CodeFusion Labs",
    logo: "/public/innovation-lab-logo.png",
    location: "Bengaluru",
    industry: "Software",
    description: "AI-powered automation and ML product development.",
    employees: 1700,
    founded: 2018,
    website: "www.codefusionlabs.com",
    revenue: "$90M",
    rating: 4.7,
    followers: 95000,
  },
  {
    id: "209",
    name: "DevOps Central India",
    logo: "/data-analytics-logo.jpg",
    location: "Bengaluru",
    industry: "Software",
    description: "Specialists in DevOps, CI/CD and cloud infrastructure.",
    employees: 2000,
    founded: 2017,
    website: "www.devopscentral.in",
    revenue: "$130M",
    rating: 4.6,
    followers: 88000,
  },
  {
    id: "210",
    name: "Bengaluru LogicSoft",
    logo: "/public/tech-company-logo.jpg",
    location: "Bengaluru",
    industry: "Software",
    description: "Custom ERP development and enterprise software services.",
    employees: 2200,
    founded: 2014,
    website: "www.bengalurulogicsoft.com",
    revenue: "$160M",
    rating: 4.5,
    followers: 92000,
  },

  // ----------------- Hyderabad (5) -----------------
  {
    id: "211",
    name: "Hyderabad AppWorks",
    logo: "/renewable-energy-logo.jpg",
    location: "Hyderabad",
    industry: "Software",
    description: "Mobile app development and high-scale backend systems.",
    employees: 1800,
    founded: 2016,
    website: "www.hydappworks.com",
    revenue: "$130M",
    rating: 4.6,
    followers: 89000,
  },
  {
    id: "212",
    name: "TechBridge Hyderabad",
    logo: "/public/innovation-lab-logo.png",
    location: "Hyderabad",
    industry: "Software",
    description: "SaaS modernization, cloud architecture and data platforms.",
    employees: 2100,
    founded: 2017,
    website: "www.techbridgehyd.com",
    revenue: "$150M",
    rating: 4.7,
    followers: 92000,
  },
  {
    id: "213",
    name: "Hyderabad SoftCore",
    logo: "/data-analytics-logo.jpg",
    location: "Hyderabad",
    industry: "Software",
    description: "Digital engineering and product innovation studio.",
    employees: 2300,
    founded: 2018,
    website: "www.softcorehyd.com",
    revenue: "$170M",
    rating: 4.6,
    followers: 94000,
  },
  {
    id: "214",
    name: "AppMatrix India",
    logo: "/public/tech-company-logo.jpg",
    location: "Hyderabad",
    industry: "Software",
    description: "Building scalable enterprise platforms and automation tools.",
    employees: 2000,
    founded: 2019,
    website: "www.appmatrix.in",
    revenue: "$110M",
    rating: 4.5,
    followers: 82000,
  },
  {
    id: "215",
    name: "HydCode Solutions",
    logo: "/public/healthcare-technology-logo.jpg",
    location: "Hyderabad",
    industry: "Software",
    description: "Custom cloud apps and end-to-end enterprise solutions.",
    employees: 1600,
    founded: 2020,
    website: "www.hydcodesol.com",
    revenue: "$95M",
    rating: 4.6,
    followers: 78000,
  },

  // ----------------- Chennai (5) -----------------
  {
    id: "216",
    name: "Chennai ProSoftware",
    logo: "/construction-industry-logo.jpg",
    location: "Chennai",
    industry: "Software",
    description:
      "Enterprise-grade web platforms and integrated SaaS solutions.",
    employees: 1900,
    founded: 2016,
    website: "www.chennaiprosoft.com",
    revenue: "$110M",
    rating: 4.5,
    followers: 84000,
  },
  {
    id: "217",
    name: "CodeMatrix Chennai",
    logo: "/public/tech-company-logo.jpg",
    location: "Chennai",
    industry: "Software",
    description: "AI integration, ML models and digital engineering.",
    employees: 2100,
    founded: 2017,
    website: "www.codematrixchennai.com",
    revenue: "$140M",
    rating: 4.6,
    followers: 91000,
  },
  {
    id: "218",
    name: "Chennai WebLabs",
    logo: "/public/innovation-lab-logo.png",
    location: "Chennai",
    industry: "Software",
    description: "Building modern web, mobile and cloud applications.",
    employees: 1700,
    founded: 2018,
    website: "www.chennaiweblabs.in",
    revenue: "$105M",
    rating: 4.5,
    followers: 76000,
  },
  {
    id: "219",
    name: "StackForge Chennai",
    logo: "/data-analytics-logo.jpg",
    location: "Chennai",
    industry: "Software",
    description: "Product engineering and platform-based enterprise solutions.",
    employees: 2000,
    founded: 2019,
    website: "www.stackforgechennai.com",
    revenue: "$125M",
    rating: 4.6,
    followers: 83000,
  },
  {
    id: "220",
    name: "SoftEra Tech",
    logo: "/public/tech-company-logo.jpg",
    location: "Chennai",
    industry: "Software",
    description: "Cloud applications and digital solutions for enterprises.",
    employees: 1800,
    founded: 2020,
    website: "www.softeratech.in",
    revenue: "$90M",
    rating: 4.4,
    followers: 70000,
  },

  // ----------------- Pune (5) -----------------
  {
    id: "221",
    name: "Pune DevSystems",
    logo: "/renewable-energy-logo.jpg",
    location: "Pune",
    industry: "Software",
    description: "Large-scale enterprise systems and API-based platforms.",
    employees: 2400,
    founded: 2016,
    website: "www.punedevsystems.com",
    revenue: "$140M",
    rating: 4.6,
    followers: 88000,
  },
  {
    id: "222",
    name: "CloudByte Pune",
    logo: "/public/innovation-lab-logo.png",
    location: "Pune",
    industry: "Software",
    description: "DevOps, SRE, API integration and SaaS modernization.",
    employees: 1900,
    founded: 2017,
    website: "www.cloudbytepune.com",
    revenue: "$120M",
    rating: 4.5,
    followers: 76000,
  },
  {
    id: "223",
    name: "Pune CodeArena",
    logo: "/data-analytics-logo.jpg",
    location: "Pune",
    industry: "Software",
    description: "Custom software development and enterprise integrations.",
    employees: 2200,
    founded: 2015,
    website: "www.punecodearena.in",
    revenue: "$150M",
    rating: 4.6,
    followers: 83000,
  },
  {
    id: "224",
    name: "SoftCraft Pune",
    logo: "/public/tech-company-logo.jpg",
    location: "Pune",
    industry: "Software",
    description: "Building secure cloud-native enterprise applications.",
    employees: 1800,
    founded: 2018,
    website: "www.softcraftpune.com",
    revenue: "$105M",
    rating: 4.5,
    followers: 77000,
  },
  {
    id: "225",
    name: "TechLogix Pune",
    logo: "/public/innovation-lab-logo.png",
    location: "Pune",
    industry: "Software",
    description: "Digital product engineering and advanced UI/UX development.",
    employees: 2100,
    founded: 2019,
    website: "www.techlogixpune.in",
    revenue: "$115M",
    rating: 4.6,
    followers: 82000,
  },

  // ----------------- Noida (5) -----------------
  {
    id: "226",
    name: "Noida Software Hub",
    logo: "/public/tech-company-logo.jpg",
    location: "Noida",
    industry: "Software",
    description: "Cloud platforms, enterprise apps and automation services.",
    employees: 2000,
    founded: 2016,
    website: "www.noidasoftwarehub.com",
    revenue: "$130M",
    rating: 4.4,
    followers: 77000,
  },
  {
    id: "227",
    name: "NorthCode Systems",
    logo: "/data-analytics-logo.jpg",
    location: "Noida",
    industry: "Software",
    description: "APIs, microservices, and modern distributed systems.",
    employees: 1800,
    founded: 2017,
    website: "www.northcodesystems.in",
    revenue: "$110M",
    rating: 4.5,
    followers: 70000,
  },
  {
    id: "228",
    name: "Noida AppForge",
    logo: "/public/innovation-lab-logo.png",
    location: "Noida",
    industry: "Software",
    description: "Mobile, cloud and custom software product development.",
    employees: 2200,
    founded: 2014,
    website: "www.noidaappforge.com",
    revenue: "$160M",
    rating: 4.6,
    followers: 86000,
  },
  {
    id: "229",
    name: "DeltaSoft Noida",
    logo: "/public/tech-company-logo.jpg",
    location: "Noida",
    industry: "Software",
    description: "Enterprise platforms and integrated SaaS applications.",
    employees: 1700,
    founded: 2019,
    website: "www.deltasoftnoida.com",
    revenue: "$95M",
    rating: 4.4,
    followers: 68000,
  },
  {
    id: "230",
    name: "SoftMatrix India",
    logo: "/public/innovation-lab-logo.png",
    location: "Noida",
    industry: "Software",
    description: "Secure cloud products and enterprise digital solutions.",
    employees: 1900,
    founded: 2020,
    website: "www.softmatrixindia.in",
    revenue: "$100M",
    rating: 4.5,
    followers: 72000,
  },
];

export const industries = [
  "All",
  "Technology",
  "Software",
  "Consulting",
  "Finance",
];

export const locations = [
  "All",
  "Mumbai",
  "Bengaluru",
  "Noida",
  "Hyderabad",
  "Chennai",
  "Pune",
  "Gurgaon",
];
