import type { Company } from "../components/models/company";

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "TechVision Corp",
    logo: "/public/tech-company-logo.jpg",
    location: "San Francisco, CA",
    industry: "Technology",
    description:
      "Leading cloud infrastructure and AI solutions provider for enterprises worldwide.",
    employees: 15000,
    founded: 2010,
    website: "www.techvision.com",
    revenue: "$5.2B",
    rating: 4.8,
    followers: 245000,
  },
  {
    id: "2",
    name: "InnovateLabs",
    logo: "/public/innovation-lab-logo.png",
    location: "New York, NY",
    industry: "Software",
    description:
      "Cutting-edge software development studio specializing in AI and machine learning.",
    employees: 3500,
    founded: 2015,
    website: "www.innovatelabs.io",
    revenue: "$820M",
    rating: 4.6,
    followers: 125000,
  },
  {
    id: "3",
    name: "GreenEnergy Solutions",
    logo: "/public/renewable-energy-logo.jpg",
    location: "Copenhagen, Denmark",
    industry: "Energy",
    description:
      "Renewable energy company focused on sustainable power solutions globally.",
    employees: 8200,
    founded: 2008,
    website: "www.greenenergy.dk",
    revenue: "$1.8B",
    rating: 4.7,
    followers: 189000,
  },
  {
    id: "4",
    name: "FinanceFlow",
    logo: "/public/fintech-logo.png",
    location: "London, UK",
    industry: "Finance",
    description:
      "Revolutionizing financial technology with blockchain and digital banking solutions.",
    employees: 2100,
    founded: 2018,
    website: "www.financeflow.co.uk",
    revenue: "$450M",
    rating: 4.5,
    followers: 98000,
  },
  {
    id: "5",
    name: "HealthTech Innovations",
    logo: "/public/healthcare-technology-logo.jpg",
    location: "Boston, MA",
    industry: "Healthcare",
    description:
      "Advanced medical technology company developing AI-powered diagnostic tools.",
    employees: 5600,
    founded: 2012,
    website: "www.healthtech.com",
    revenue: "$950M",
    rating: 4.9,
    followers: 156000,
  },
  {
    id: "6",
    name: "BuildCraft Industries",
    logo: "/public/construction-industry-logo.jpg",
    location: "Singapore",
    industry: "Construction",
    description:
      "Smart construction and real estate development with IoT integration.",
    employees: 4200,
    founded: 2014,
    website: "www.buildcraft.sg",
    revenue: "$720M",
    rating: 4.4,
    followers: 87000,
  },
  {
    id: "7",
    name: "RetailMax",
    logo: "/public/retail-commerce-logo.jpg",
    location: "Toronto, Canada",
    industry: "Retail",
    description:
      "E-commerce and retail platform connecting millions of buyers and sellers.",
    employees: 9800,
    founded: 2009,
    website: "www.retailmax.ca",
    revenue: "$3.1B",
    rating: 4.3,
    followers: 201000,
  },
  {
    id: "8",
    name: "CloudNine Analytics",
    logo: "/public/data-analytics-logo.jpg",
    location: "Seattle, WA",
    industry: "Technology",
    description:
      "Big data analytics and business intelligence platform for data-driven decisions.",
    employees: 1800,
    founded: 2016,
    website: "www.cloudnine.io",
    revenue: "$320M",
    rating: 4.7,
    followers: 112000,
  },
];

export const industries = [
  "All Industries",
  "Technology",
  "Software",
  "Energy",
  "Finance",
  "Healthcare",
  "Construction",
  "Retail",
];

export const locations = [
  "All Locations",
  "San Francisco, CA",
  "New York, NY",
  "Boston, MA",
  "Seattle, WA",
  "London, UK",
  "Copenhagen, Denmark",
  "Singapore",
  "Toronto, Canada",
];
